Sprint1/step2
I194/ya-react-burger pull request #2
Opened 2021-08-19 14:22 UTC by I194

Добавлено модальное окно и загрузка данных с сервера.

2021-08-19 15:44 UTC, SmilingJey requested changes
Здравствуйте!

Хорошая работа, проект почти полностью соответствует макету, реализовано открытие попапов через портал, но есть несколько замечаний в реализации функционала:

**Основные места, которые нужно исправить:**

- в коде очень сложно ориентироваться, т.к. файлы перегружены вынесите компоненты в отдельный файл, как минимум компоненты - OrderDetails Ingredient IngredientDetails ModalOverlay должны быть в отдельных файлах, более мелкие компоненты можно оставить в самих файлах этих компонентов, но старайтесь, что бы их было не больше 2-3

- для всех необходимых для отображения компонента пропсов в propTypes должен задаваться `.isRequired`

- ширина меню в шапке такая же как и ширина контента страницы https://yadi.sk/i/zY089tQuvt2mpw

- при фильтрации ингредиентов по категориям используйте filter

- добавьте проверку ответа сервера - res.ok

**Более мелкие замечания и места, в которых можно улучшить проект так же отмечены в коде:**

2021-08-19 15:44 UTC, SmilingJey commented on src/components/App/App.tsx
> +const API = 'https://norma.nomoreparties.space/api/ingredients ';
**Можно лучше**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2021-08-19 15:44 UTC, SmilingJey commented on src/components/App/App.tsx
> +    const getAPIdata = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2021-08-19 15:44 UTC, SmilingJey commented on src/components/App/App.tsx
> +        const data = await res.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2021-08-19 15:44 UTC, SmilingJey commented on src/components/App/App.tsx
> +    <>
**Можно лучше**
эта обёртка `<>` лишняя, оборачивать в React.Fragment требуется, только если в компонент содержит несколько невложенных блоков, например

```
<>
  <div>.....</div>
  <div>.....</div>
</>

```

[https://ru.reactjs.org/docs/fragments.html](https://ru.reactjs.org/docs/fragments.html)

2021-08-19 15:44 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.js
> +  image_large: PropTypes.string,
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов
```
image_large: PropTypes.string.isRequired
```

без этого не контролируется, что пропс передается

Проверьте во всем проекте

2021-08-19 15:44 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.js
> +  const buns = [], mains = [], sauces = [];
**Надо исправить**

Используйте filter для фильтрации, 
Например:

```
const buns = useMemo(data.filter((item) => item.type === 'buns'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

2021-08-19 15:44 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.js
> +  const [current, setCurrent] = useState('buns');
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
[https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView](https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView)

2021-08-20 18:15 UTC, I194 commented
Всё исправил и доделал; 
.isRequired проставил везде, где это было необходимо.

2021-08-20 19:08 UTC, SmilingJey approved these changes
Отлично, замечания исправлены, с разбивкой компонентов по файлом стало гораздо легче ориентироваться в коде

Отметил несколько мест, где можно ещё улучшить код

Успехов в дальнейшем обучении!

2021-08-20 19:08 UTC, SmilingJey commented on src/utils/burger-api.js
> +export default async function getData(url) {
**Можно лучше**

лучше перенести константу BURGER_API_URL в этот файл и сделать функцию более конкретизированной - getIngredients

```
const BURGER_API_URL = 'https://norma.nomoreparties.space/api';

export default function getIngredients() {
  return fetch(`${BURGER_API_URL}/ingredients`)
    .then(checkReponse)
    .then(data =>data.data)
}

```

В App 
```
  useEffect(() => {
    const loadIngredients = async () => {
      const ingredients: any = await getIngredients();
      setData(ingredients);
    };
    loadIngredients();
  }, []);
```

2021-08-20 19:08 UTC, SmilingJey commented on src/components/BurgerConstructor/BurgerConstructor.js
> +      <Modal header={''} isVisible={modalVisible} onClose={handleCloseModal} box={{w: '720px', h: '720px'}}>
**Можно лучше**

сейчас компонент модального окна присутствует в дереве, даже если окно закрыто

![2021-08-20_22-03-18](https://user-images.githubusercontent.com/9317133/130281774-aa83c216-67e0-4005-ac60-0e6d705ff64b.png)

Лучше не управлять видимостью окна внутри Modal, а просто не рендерить Modal если попап закрыт

```
{
      modalVisible && (<Modal header={''} onClose={handleCloseModal} box={{w: '720px', h: '720px'}}>
        <OrderDetails {...modalData}/>
      </Modal>
)}
```

2021-08-20 19:08 UTC, SmilingJey commented on src/components/BurgerIngredients/BurgerIngredients.js
> +      <Modal header={'Детали ингредиента'} isVisible={modalVisible} onClose={handleCloseModal} box={{w: '720px', h: '540px'}}>
**Можно лучше**

сейчас компонент модального окна присутствует в дереве, даже если окно закрыто

![2021-08-20_22-03-18](https://user-images.githubusercontent.com/9317133/130281774-aa83c216-67e0-4005-ac60-0e6d705ff64b.png)

Лучше не управлять видимостью окна внутри Modal, а просто не рендерить Modal если попап закрыт

```
{
      modalVisible && (<Modal header={'Детали ингредиента'} onClose={handleCloseModal} box={{w: '720px', h: '540px'}}>
        {modalVisible && <IngredientDetails {...modalData}/>}
      </Modal>
)}
```

2021-08-21 19:34 UTC, merged